### PR TITLE
[example][apollo-client][react-navigation] fix type errors

### LINKED ISSUE #70: Mismatch between useReactNavigationDevTools and React Navigation container
Applying the example to a latest React Navigation and Expo project got me this error.

Image

Image

I believe this happens due to React Navigation having this type as the returned navigationRef

```typescript
export type NavigationContainerRefWithCurrent<ParamList extends {}> =
  NavigationContainerRef<ParamList> & {
    current: NavigationContainerRef<ParamList> | null;
  };
```

While the dev tool expects the current property to not be null.

### PR DESCRIPTION
**Pull request by Kudo**
# Why

fix typecheck errors
fixes #70

# How

- fix nullable NavigationContainerRef from react-navigation
- for apollo-client, bun treats dependency differently for react-dom as peerDependnecy from `@apollo/client`. to workaround this, i have to add react-dom devDeps to the apollo plugin, so bun will keep the same resolution

# Test Plan

add typecheck to ci

### CODE REVIEW

File: apps/example/src/app/index.tsx [hunk 1]
```diff
@@ -8,19 +8,19 @@ export default function TesterScreen() {
...
+        <TestCase title="Vanilla Log Viewer" route="/vanilla-log-viewer" />
+        <TestCase title="Async Storage" route="/async-storage" />
+        <TestCase title="React Native MMKV" route="/react-native-mmkv" />
       </View>
     </SafeAreaView>
   );
 }
 
-function TestCase<T>({ title, route }: { title: string; route: LinkProps<T>['href'] }) {
+function TestCase({ title, route }: { title: string; route: LinkProps['href'] }) {
```
Comment (Kudo) [inline apps/example/src/app/index.tsx:23]: LinkProps is not generic type from newer expo-router

File: packages/react-navigation/src/useReactNavigationDevTools.ts [hunk 2]
```diff
@@ -5,13 +5,16 @@ import { useEffect, useRef } from 'react';
 
 import { ReduxExtensionAdapter } from './ReduxExtensionAdapter';
 
-export function useReactNavigationDevTools(ref: React.RefObject<NavigationContainerRef<any>>) {
+export function useReactNavigationDevTools(
+  ref: React.RefObject<NavigationContainerRef<any> | null>
```
Comment (Kudo) [inline packages/react-navigation/src/useReactNavigationDevTools.ts:9]: as #70

File: packages/react-navigation/src/useReactNavigationDevTools.ts [hunk 3]
```diff
@@ -5,13 +5,16 @@ import { useEffect, useRef } from 'react';
...
+) {
   const client = useDevToolsPluginClient('react-navigation');
   const adapterRef = useRef(new ReduxExtensionAdapter());
   // @ts-ignore: Override global
   globalThis.__REDUX_DEVTOOLS_EXTENSION__ = {
     connect: () => adapterRef.current,
   };
+  // @ts-ignore: useReduxDevToolsExtension does not accept null ref from NavigationContainerRefWithCurrent
```
Comment (Kudo) [inline packages/react-navigation/src/useReactNavigationDevTools.ts:17]: i guess the problem is actually from react-navigation/devtools

File: packages/apollo-client/package.json [hunk 4]
```diff
@@ -41,6 +41,7 @@
     "expo": "53.0.7",
     "expo-module-scripts": "^4.1.7",
     "graphql": "^16.9.0",
+    "react-dom": "19.1.0",
```
Comment (Kudo) [inline packages/apollo-client/package.json:44]: bun adds `@apollo/client` as different dep that example's apollo-client has react-dom peerDep and this plugin does not.
to resolve the type error, this is a workaround to add react-dom from the plugin, so that bun can treat the apollo/client as same package and same type

Comment (vonovak) [reply packages/apollo-client/package.json:44]: interesting

**Review by vonovak — APPROVED** [review]
