### PR TITLE
[async-storage]: Fix inline editing cursor jump

### LINKED ISSUE #23: @dev-plugin/async-storage inline editing cursor jump
Async storage devtools have an option to inline edit the value, but it updates the value after each keystroke, which sets the cursor at the beginning of the text input. The result is typing backwards!

For example, trying to type `testing` results into: 

image

React probably re-renders after the value change and resets the cursor.

### PR DESCRIPTION
**Pull request by Thomas-Gallant**
When attempting to update a value through async storage devtools UI, the cursor is moved to the beginning of the text input. 

This change disables re-rendering of the Value column cells as the user is typing. This issue no longer appears, and functionality of saving changes, adding and removing key-value pairs does not appear to be affected by this change. 

Fixes #23

### CODE REVIEW

**Comment by Kudo** [comment]
@jthoward64 could you help to review the change when you get a chance?

File: packages/async-storage/webui/src/AsyncStorageTable.tsx [hunk 1]
```diff
@@ -95,8 +95,8 @@ export function AsyncStorageTable() {
                 },
               };
             },
-            shouldCellUpdate(record, prevRecord) {
-              return record.editedValue !== prevRecord.editedValue;
+            shouldCellUpdate() {
+              return false;
             },
           },
           {
```
Comment (jthoward64) [inline packages/async-storage/webui/src/AsyncStorageTable.tsx:102]:
```suggestion
                onBlur() {
                  setEditingManually(false);
                },
                onFocus() {
                  setEditingManually(true);
                },
              };
            },
            shouldCellUpdate(record, prevRecord) {
              return !editingManually && record.editedValue !== prevRecord.editedValue
            },
          },
```

I added a state to check whether the user currently has focused the cell and that does seem to fix the jump issue while still keeping the json editor working

Comment (Thomas-Gallant) [reply packages/async-storage/webui/src/AsyncStorageTable.tsx:102]: My bad, I didn't realize my change would break the json editor. I'll merge in this suggestion!

Comment (Thomas-Gallant) [reply packages/async-storage/webui/src/AsyncStorageTable.tsx]: I've updated the pr, like you said the json editor seems to be working now.

Comment (jthoward64) [reply packages/async-storage/webui/src/AsyncStorageTable.tsx]: > I've updated the pr, like you said the json editor seems to be working now.

In that case this looks good to me, so long as @Kudo doesn't have any issues

**Comment by Kudo** [comment]
thanks @Thomas-Gallant and @jthoward64 for helping this change. i'm merging the pr and publish updates soon.

**Review by Kudo — APPROVED** [review]
